language: python # => 1
    python: # => 2
      - "3.6"
    env: # => 4
      -DJANGO=2.1
    install: # => 5
      - pip3 install -r requirements.txt
    script: # => 7
      - python manage.py test
